version: '3.8'

services:

  db:
    image: sl-psql:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile.psql
    networks:
      sl-net:
        ipv4_address: 172.25.0.2
    ports:
      - 8032:5432
    environment:
      POSTGRES_USER: sql-ledger
      POSTGRES_PASSWORD: sql-ledger
      POSTGRES_DB: template1
    volumes:
     - db-data:/var/lib/postgresql/data

  app:
    image: sl-app:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile.app
    networks:
      sl-net:
        ipv4_address: 172.25.0.3
    ports:
      - 8080:80
    depends_on: 
      - db

networks:
  sl-net:
    name: sl-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

volumes:
  db-data: {}
